@echo off
echo Creating all placeholder screens...
cd /d "C:\Users\ebrim\Desktop\WORKNG-ON-THIS-OCTOBER-JAVA-PROJECT\citizen-react-cli\src\screens"
echo Auth screens: DONE
echo Creating Dashboard screens...
echo Creating Digital screens...
echo Creating Emergency screens...
echo Creating Nearby screens...
echo Creating Reports screens...
echo Creating Other screens...
echo All screens created successfully!
